#!/bin/bash

#    OpenJDK Detector
#    Copyright (C) 2023 Jeffrey W. Tickle
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Find all files named `java` inside a directory named `bin` located anywhere
# on the system. Separate output with `null` instead of space, so that trees
# containing spaces or other special characters can be processed.
# Pipe this null-separated output into a bash `while read` loop, specifying a
# null delimiter.
locate -0 '*/bin/java' | while read -d $'\0' java
do
	# Find and print md5 hash of the file
	# Later, we will use the hash for classification and faster identification
	echo -n $(md5sum $java)

	# Search the binary for the case-insensitive string `openjdk`
	echo -n " "
	result=$(strings $java |grep -A 2 -i openjdk)
	if [ $? -ne 0 ]; then
		echo "unidentified"
	else
		echo $result
	fi
done
